name:                cseduosu
version:             0.1.0.0
github:              "doyougnu/cseduosu"
license:             BSD3
author:              "Qiaoran Chelsea, Alex Grejuc, Parisa Ataei, Jeffrey Young"
maintainer:          "youngjef@oregonstate.edu"
copyright:           "2018 Qiaoran Chelsea, Alex Grejuc, Parisa Ataei, Jeffrey Young"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cseduosu#readme>

dependencies:
 - base >= 4.7 && < 5
 - containers
 - mtl
 - yesod
 - ghcid

default-extensions:
  - OverloadedStrings
  - ViewPatterns
  - DeriveFunctor
  - DeriveGeneric
  - BangPatterns
  - GeneralizedNewtypeDeriving
  - DeriveTraversable


library:
  source-dirs: src

executables:
  cseduosu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cseduosu

tests:
  cseduosu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cseduosu
